name: first workflow
on: 
  workflow_dispatch: 
jobs:
  firstjob: 
    runs-on: self-hosted 
    steps:
    - name: firstJob script 
      shell: cmd
      run: echo Hello Word! This is first job
  secondjob: 
    runs-on: ubuntu-latest
    steps:
      - name: secondJob script
        shell: bash
        run: | 
          echo this issecond job
          echo and this is a multi-line script 
